---
title: Pitching
date: '`r format(Sys.Date(), "%B %d, %Y")`'
---



```{r, include=FALSE}
# Installing Libraries 
#install.packages(c("tidyr", "dplyr", "knitr", "tidyverse", "yaml"))
library("tidyr")
library("yaml")
library("dplyr")
library("knitr")
library("tidyverse")
library("tinytex")
```

```{r, include=FALSE}
# Reading Data
mudcatsRaw <- read.csv("https://raw.githubusercontent.com/bmswnson/Mudcats/main/Data/currentStats.csv")
```


```{r, include=FALSE}
# Adding Full Names
mudcatsRaw$fullName <- paste(mudcatsRaw$First, mudcatsRaw$Last, sep = " ")
```



```{r, include=FALSE}
# Subsetting Stats
pitchingSelect <- mudcatsRaw %>%
  select(fullName, Last, IP, GP, GS, W, L, SV, SVO, BS, SV, 
         H.1, R.1, ER, BB.1, SO.1, HBP.1, ERA, WHIP, BF)
```

# Team

## Tables

### IP
```{r}
ipTable <- pitchingSelect %>%
  select(Last, IP) 
as.data.frame(ipTable[order(ipTable$IP, decreasing = TRUE),])
```

### ERA
```{r}
eraTable <- pitchingSelect %>%
  filter(IP > .1) %>%
  select(Last, ERA) 
as.data.frame(eraTable[order(eraTable$ERA, decreasing = FALSE),])
```

# Individual
## Dorsey
```{r}
pitchingSelect %>%
  filter(Last == "Dorsey") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Duncan
```{r}
pitchingSelect %>%
  filter(Last == "Duncan") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Gunkel
```{r}
pitchingSelect %>%
  filter(Last == "Gunkel") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Huntington
```{r}
pitchingSelect %>%
  filter(Last == "Huntington") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Howe
## Huseby
```{r}
pitchingSelect %>%
  filter(Last == "Howe") %>%
  select(-Last, -fullName) %>%
  kable()
```


## Huseby
```{r}
pitchingSelect %>%
  filter(Last == "Huseby") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Levasseur
```{r}
pitchingSelect %>%
  filter(Last == "Levasseur") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Fagerland 
```{r}
pitchingSelect %>%
  filter(Last == "Fagerland") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Liking
```{r}
pitchingSelect %>%
  filter(Last == "Liking") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Naugs
```{r}
pitchingSelect %>%
  filter(Last == "Naugle") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Pill
```{r}
pitchingSelect %>%
  filter(Last == "Pilon") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Reed
```{r}
pitchingSelect %>%
  filter(Last == "Reed") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Big Chungus
```{r}
pitchingSelect %>%
  filter(Last == "Sayles") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Schwinner
```{r}
pitchingSelect %>%
  filter(Last == "Stratton") %>%
  select(-Last, -fullName) %>%
  kable()
```

## B Weids
```{r}
pitchingSelect %>%
  filter(Last == "Weidieman") %>%
  select(-Last, -fullName) %>%
  kable()
```
