---
title:All Possible Stats
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Offense
GP = Games played	
PA = Plate appearances
AB = At bats
H = Hits	
1B = Singles
2B = Doubles	
3B = Triples	
HR = Home runs
RBI = Runs batted in
R = Runs scored	
HBP = Hit by pitch
ROE = Reached on error
FC = Hit into fielder's choice
CI = Batter advances on catcher's interference	
BB = Base on balls (walks)	
SO = Strikeouts	
AVG = Batting average (season)
OBP = On-base percentage (season)
SLG = Slugging percentage	
OPS = On-base percentage plus slugging percentage (season)
PA/BB = Plate appearances per walk	
BB/K = Walks per strikeout
C% = Contact rate	
K-L = Strikeouts Looking
SB = Stolen bases
CS = Caught stealing	
SB% = Stolen base percentage
PIK = Picked off
GIDP = Hit into double play	
GITP = Hit into triple play	
XBH = Extra-base hits	
TB = Total bases	
AB/HR = At bats per home run
BA/RISP = Batting average with runners in scoring position	
PS = Pitches seen	
PS/PA = Pitches seen per plate appearance	
2S+3 = Plate appearances in which batter sees 3+ pitches after 2 strikes	
2S+3% = % of plate appearances in which batter sees 3+ pitches after 2 strikes
6+ = Plate appearances with 6+ pitches	
6+% = % of plate appearances of 6+ pitches	
FLB% = Fly ball percentage	
GB% = Ground ball percentage
SAC = Sacrifice hits & bunts
SF = Sacrifice flies	
LOB = Runners left on base when batter is out	2OUTRBI = 
2-out RBI	HHB = Hard hit balls: Total line drives and hard ground balls	
QAB = Quality at bats (any one of: 3 pitches after 2 strikes, 6+ pitch ABs, XBH, HHB, BB, SAC Bunt, SAC Fly)
QAB% = Quality at bats per plate appearance	
BABIP = Batting average on balls in play

# Pitching
IP = Innings Pitched
GP = Games pitched	
GS = Games started as the pitcher
W = Wins
L = Losses
SV = Saves	
SVO = Save opportunities
BS = Blown saves	
SV% = Save percentage	
H = Hits allowed	
R = Runs allowed	
ER = Earned runs allowed	
BB = Base on balls (walks)
SO = Strikeouts	
HBP = Hit batters	
ERA = Earned run average (season)
WHIP = Walks plus hits per innings pitched
BF = Total batters faced	#P = Total pitches
TS = Total strikes
TB = Total balls
P/IP = Pitches per inning
P/BF = Pitches per batter faced	<3 = Batters on or out in three pitches or less	<3% = % of batters on or out in three pitches or less	
LOO = Leadoff out (1st batter of inning)
1ST2OUT = Innings with 1st 2 batters out	
123INN =  1-2-3 Innings	<13 = Innings of 13 pitches or fewer
FIP = Fielding Independent Pitching	S% = Strike percentage
FPS = First pitch strikes	FPS% = First pitch strike percentage	
FPSO% = % of FPS at-bats that result in an out	
FPSW% = % of FPS at-bats that result in a walk	
FPSH% = % of FPS at-bats that result in a hit	
BB/INN = Walks per inning
0BBINN = Zero-walk innings	
BBS = Walks that score	
LOBB = Leadoff walk (1st batter of inning)
LOBBS = Leadoff walk that scored (1st batter of inning)
WP = Wild pitches	
ABA = At Bats against	
SM = Opposing batter swings-and-misses	
SM% = % of total pitches that are swings and misses	
K/G = Strikeouts per regulation game	
K/BF = Strikeouts per batter faced
K/BB = Strikeouts per walk	
WEAK% = % of batted balls weakly hit (fly balls and ground balls)	
HHB% = % of batted balls that are line drives or hard ground balls
GB% = % of all batted balls hit on the ground	
FLB% = % of batted balls that are hit in the air
GO = Ground outs	FO = Fly outs	
GO/FO = Ratio of ground outs to fly outs	
BAA = Opponent batting average
HR = Home runs allowed	
BABIP = Opponent batting average on balls in play
LOB = Runners left on base	BK = Balks	
PIK = Runners picked off	
SB = Stolen bases allowed	
CS = Runners caught stealing
SB% = Opponent stolen base percentage
FB = Number of pitches thrown as Fastballs
FBS = Number of Fastballs thrown for strikes	
FBS% = Percentage of Fastballs thrown for strikes	
CT = Number of pitches thrown as Cutters	
CTS = Number of Cutters thrown for strikes	
CTS% = Percentage of Cutters thrown for strikes	
CB = Number of pitches thrown as Curveballs	
CBS = Number of Curveballs thrown for strikes	
CBS% = Percentage of Curveballs thrown for strikes
SL = Number of pitches thrown as Sliders	
SLS = Number of Sliders thrown for strikes	
SLS% = Percentage of Sliders thrown for strikes	
CH = Number of pitches thrown as Changeups
CHS = Number of Changeups thrown for strikes
CHS% = Percentage of Changeups thrown for strikes
OS = Number of pitches thrown Offspeed (Curveball, Screwball, Changeup)	
OSS = Number of pitches thrown Offspeed for strikes	
OSS% = Percentage of Offspeed pitches thrown as strikes	TC = Total Chances 

# Defense
A = Assists	
PO = Putouts	
E = Errors	
DP = Double Plays	
TP = Triple Plays	
FPCT = Fielding Percentage
cINN = Innings caught
cPB = Passed balls allowed	
cSB = Stolen bases allowed
cCS = Runners caught stealing	
cCS% = Runners caught stealing percentage	
cPIK = Runners picked off	cCI = Batter advances on catcher's interference