---
title: "Mudcats Stats"
author: "Ben Swanson"
date: "5/31/2022"
output:
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
    code_folding: hide
    df_print: paged
  pdf_document:
    toc: yes
---


# Installing Libraries 
```{r, include=FALSE}
#install.packages(c("tidyr", "dplyr", "knitr", "tidyverse", "yaml"))
library("tidyr", "dplyr", "knitr", "tidyverse")
library("yaml")

```

```{r, include=FALSE}
# Reading Data
mudcatsRaw <- read_csv(file.path(path, "/Github/Mudcats/Data/seasonStats_2022-05-26.csv"))
```

# Adding Full Names
```{r, include=FALSE}
mudcatsRaw$fullName <- paste(mudcatsRaw$First, mudcatsRaw$Last, sep = " ")

mudcatsRaw <- mudcatsRaw %>%
  rename("GPoffense" = GP...4, 
         "Hoffense" = H...7, 
         "HRoffesne" = HR...11, 
         "Roffesne" = R...13, 
         "HBPoffense" = HBP...14, 
         "BBoffense" = BB...18, 
         "SOoffesne" = SO...19,
         #Defense
         "GPdefense" = GP...55, 
         "Hdefense" = H...63, 
         "HRdefense" = HR...110, 
         "Rdefense" = R...64, 
         "HBPdefense" = HBP...68, 
         "BBdefense" = BB...66, 
         "SOdefense" = SO...67)
```


# Subsetting Stats
```{r, include=FALSE}
offense <- mudcatsRaw %>% 
  select(Last, GPoffense, PA, AB, Hoffense, "1B", "2B", "3B", HRoffesne, RBI,
         Roffesne, HBPoffense, AVG, ROE, FC, OBP, SLG, OPS)

offenseSelect <- mudcatsRaw %>%
  select(fullName, Last, GPoffense, PA, AB, Hoffense, "1B", "2B", "3B", HRoffesne, RBI,
         Roffesne, HBPoffense, AVG, SLG, OPS, OBP)
 

pitchingSelect <- mudcatsRaw %>%
  select(fullName, Last, IP, GPdefense, GS, W, L, SV, SVO, BS, SV, 
         Hdefense, Rdefense, ER, BBdefense, SOdefense, HBPdefense, ERA, WHIP, BF)
```



# Offensive Stats

## Team Leaders

### Average
```{r}
offenseSelect %>% 
  filter(quantile(AVG, .9) < AVG) %>%
  select(fullName, AVG) %>%
  kable()
```

### OPS
```{r}
offenseSelect %>% 
  filter(quantile(OPS, .9) < OPS) %>%
  select(fullName, OPS) %>%
  kable()
```

### OBP
```{r}
offenseSelect %>% 
  filter(quantile(OBP, .9) < OBP) %>%
  select(fullName, OBP) %>%
  kable()
```




# Individual Stats
## Dorsey
```{r}
offenseSelect %>%
  filter(Last == "Dorsey") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Gunkel
```{r}
offenseSelect %>%
  filter(Last == "Gunkel") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Huntington
```{r}
offenseSelect %>%
  filter(Last == "Huntington") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Huseby
```{r}
offenseSelect %>%
  filter(Last == "Huseby") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Liking
```{r}
offenseSelect %>%
  filter(Last == "Liking") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Naugs
```{r}
offenseSelect %>%
  filter(Last == "Naugle") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Pill
```{r}
offenseSelect %>%
  filter(Last == "Pilon") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Reed
```{r}
offenseSelect %>%
  filter(Last == "Reed") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Big Chungus
```{r}
offenseSelect %>%
  filter(Last == "Sayles") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Schwinner
```{r}
offenseSelect %>%
  filter(Last == "Stratton") %>%
  select(-Last, -fullName) %>%
  kable()
```

## B Weids
```{r}
offenseSelect %>%
  filter(Last == "Weidieman") %>%
  select(-Last, -fullName) %>%
  kable()
```












# Pitiching

# Individual Stats
## Dorsey
```{r}
pitchingSelect %>%
  filter(Last == "Dorsey") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Gunkel
```{r}
pitchingSelect %>%
  filter(Last == "Gunkel") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Huntington
```{r}
pitchingSelect %>%
  filter(Last == "Huntington") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Huseby
```{r}
pitchingSelect %>%
  filter(Last == "Huseby") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Liking
```{r}
pitchingSelect %>%
  filter(Last == "Liking") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Naugs
```{r}
pitchingSelect %>%
  filter(Last == "Naugle") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Pill
```{r}
pitchingSelect %>%
  filter(Last == "Pilon") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Reed
```{r}
pitchingSelect %>%
  filter(Last == "Reed") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Big Chungus
```{r}
pitchingSelect %>%
  filter(Last == "Sayles") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Schwinner
```{r}
pitchingSelect %>%
  filter(Last == "Stratton") %>%
  select(-Last, -fullName) %>%
  kable()
```

## B Weids
```{r}
pitchingSelect %>%
  filter(Last == "Weidieman") %>%
  select(-Last, -fullName) %>%
  kable()
```
