---
title: "Offense"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
---



```{r, include=FALSE}
# Installing Libraries 
#install.packages(c("tidyr", "dplyr", "knitr", "tidyverse", "yaml"))
library("tidyr")
library("yaml")
library("dplyr")
library("knitr")
library("tidyverse")
library("tinytex")
library("ggplot2")
```

```{r, include=FALSE}
# Reading Data
mudcatsRaw <- read.csv("https://raw.githubusercontent.com/bmswnson/Mudcats/main/Data/currentStats.csv")
```


```{r, include=FALSE}
# Adding Full Names
mudcatsRaw$fullName <- paste(mudcatsRaw$First, mudcatsRaw$Last, sep = " ")
```



```{r, include=FALSE}
# Subsetting Stats
offense <- mudcatsRaw %>% 
  select(Last, GP, PA, AB, H, X1B, X2B, X3B, HR, RBI,
         R, HBP, AVG, ROE, FC, OBP, SLG, OPS, PA.BB, 
         BB.K, C., K.L, SB, CS, SB.)
offenseSelect <- mudcatsRaw %>%
  select(fullName, Last, AVG, GP, PA, AB, H, X1B, X2B, X3B, HR, RBI,
         R, HBP,  SLG, OPS, OBP) %>% 
  rename("singles" = X1B, 
         "doubles" = X2B, 
         "triples" = X3B) 
```



# Offensive

## Team Leaders

### Average
```{r}
offenseSelect %>% 
  filter(quantile(AVG, .9) < AVG) %>%
  select(fullName, AVG) %>%
  kable()
```

### OPS
```{r}
offenseSelect %>% 
  filter(quantile(OPS, .9) < OPS) %>%
  select(fullName, OPS) %>%
  kable()
```

### OBP
```{r}
offenseSelect %>% 
  filter(quantile(OBP, .9) < OBP) %>%
  select(fullName, OBP) %>%
  kable()
```

## Graphs

### Average
```{r}
ggplot(data = offenseSelect, aes(x = fullName, y = AVG, label = Last)) + 
  geom_text(size = 2.5, vjust = 2) +
  geom_point() + 
  scale_y_binned(breaks = seq(0,1,.05)) +
  scale_x_discrete(expand = c(.04, .08)) +
  theme(axis.text.x = element_text(angle = 90, size = 0)) + 
  ggtitle(paste("Team Averages"))
  
```



# Individual Stats
## Dorsey
```{r}
offenseSelect %>%
  filter(Last == "Dorsey") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Gunkel
```{r}
offenseSelect %>%
  filter(Last == "Gunkel") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Gravy
```{r}
offenseSelect %>%
  filter(Last == "Gravdahl ") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Tommy
```{r}
offenseSelect %>%
  filter(Last == "Horan ") %>%
  select(-Last, -fullName) %>%
  kable()
```


## Howe
```{r}
offenseSelect %>%
  filter(Last == "Howe") %>%
  select(-Last, -fullName) %>%
  kable()
```


## Huntington
```{r}
offenseSelect %>%
  filter(Last == "Huntington") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Huseby
```{r}
offenseSelect %>%
  filter(Last == "Huseby") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Liking
```{r}
offenseSelect %>%
  filter(Last == "Liking") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Naugs
```{r}
offenseSelect %>%
  filter(Last == "Naugle") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Pill
```{r}
offenseSelect %>%
  filter(Last == "Pilon") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Reed
```{r}
offenseSelect %>%
  filter(Last == "Reed") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Big Chungus
```{r}
offenseSelect %>%
  filter(Last == "Sayles") %>%
  select(-Last, -fullName) %>%
  kable()
```

## Schwinner
```{r}
offenseSelect %>%
  filter(Last == "Stratton") %>%
  select(-Last, -fullName) %>%
  kable()
```

## B Weids
```{r}
offenseSelect %>%
  filter(Last == "Weidieman") %>%
  select(-Last, -fullName) %>%
  kable()
```

